Add information on libseccomp version (Raspbian Buster - Docker)
owncloud/docs pull request #3196
Opened 2021-02-22 22:42 UTC by CalvinSchwartz

The Owncloud Docker Version 10.5 and 10.6 won't work due to an permission error caused by an old version of libseccomp.
See https://github.com/owncloud-docker/server/issues/219

2021-02-23 11:01 UTC, mmattel commented on modules/admin_manual/pages/installation/docker/index.adoc
> +If your container fails to start on a Raspberry Pi or other ARM device you most likely have an old version of Libseccomp2 on your host. This should only affect Rasbian Buster 32 bit. Install a never
```suggestion
If your container fails to start on a Raspberry Pi or other ARM device, you most likely have an old version of `libseccomp2` on your host. This should only affect Rasbian Buster 32 bit. Install a never version with the following command:
```

2021-02-23 11:02 UTC, mmattel commented
In case, backport to **10.5** and **master** necessary

2021-02-23 11:04 UTC, JanAckermann commented on modules/admin_manual/pages/installation/docker/index.adoc
> +If your container fails to start on a Raspberry Pi or other ARM device you most likely have an old version of Libseccomp2 on your host. This should only affect Rasbian Buster 32 bit. Install a never
updated never -> newer

2021-02-23 11:08 UTC, mmattel commented
@JanAckermann can you check if the changes proposed are correct or if it needs additional changes like mentioned in the PR description on top?

2021-02-23 11:09 UTC, JanAckermann approved these changes

2021-02-23 11:10 UTC, JanAckermann commented
@mmattel which PR?

2021-02-23 11:12 UTC, mmattel commented
> which PR?

this one 😄

2021-02-23 11:28 UTC, JanAckermann requested changes

2021-02-23 11:28 UTC, JanAckermann commented on modules/admin_manual/pages/installation/docker/index.adoc
> +If your container fails to start on a Raspberry Pi or other ARM device, you most likely have an old version of `libseccomp2` on your host. This should only affect Rasbian Buster 32 bit. Install a new
```suggestion
If your container fails to start on a Raspberry Pi or other ARM device, you most likely have an old version of `libseccomp2` on your host. This should only affect distros based on Rasbian Buster 32 bit. Install a newer version with the following command:
```

2021-02-23 12:46 UTC, JanAckermann commented
@mmattel I am on it, but my virtual box making trouble ;)

2021-02-23 19:22 UTC, mmattel commented on modules/admin_manual/pages/installation/docker/index.adoc
> +wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
```suggestion
cd /tmp
wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
```

2021-02-24 08:18 UTC, JanAckermann approved these changes

2021-02-24 08:23 UTC, JanAckermann commented
@mmattel is was not able to reproduce it now, as my Debian Buster VM Box won't start properly.

But i'll try again, 
maybe solution 3 is better:
https://docs.linuxserver.io/faq

2021-02-24 08:53 UTC, mmattel commented on modules/admin_manual/pages/installation/docker/index.adoc
> +----
```suggestion
----

Alternatively you can add the backports repo for DebianBuster:

[source,console]
 ----
 sudo apt-key adv --keyserver keyserver.ubuntu.com \
      --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
 echo "deb http://deb.debian.org/debian buster-backports main" | \
      sudo tee -a /etc/apt/sources.list.d/buster-backports.list
 sudo apt update
 sudo apt install -t buster-backports libseccomp2
 ----
 
 In any case, you should need to restart the container after confirming you have libseccomp2.4.4 installed.
 
 For more information see: https://docs.linuxserver.io/faq
```

2021-02-24 08:55 UTC, mmattel commented on modules/admin_manual/pages/installation/docker/index.adoc
> +----
@JanAckermann pls check the proposed changes and commit if ok.
If all is fine, it looks good to merge and backport to 10.5 and master

2021-02-24 09:21 UTC, mmattel approved these changes

2021-02-24 11:15 UTC, phil-davis approved these changes

2021-02-24 11:16 UTC, phil-davis commented
I rebased and squashed. I will merge when CI finishes, and make ports to `master` and `10.5`

2021-02-24 11:28 UTC, merged

2021-03-12 10:55 UTC, voroyam commented
![image](https://user-images.githubusercontent.com/24212810/110930799-d7a8e500-8329-11eb-8962-4140f945a994.png)

2021-03-12 10:56 UTC, voroyam commented
There is an extra space there, disturbing the code block being rendered correctly...

2021-03-12 11:06 UTC, voroyam commented
https://github.com/owncloud/docs/pull/3338

2021-03-12 11:12 UTC, voroyam commented
seems like no one tested this PR on an Antora server, most of the mistakes could have been prevented.