Update ms-azure-setup.adoc
owncloud/docs pull request #3492
Opened 2021-04-19 16:20 UTC by ib-mlatin

Make a note that the desktop/mobile apps do not work by default with Azure AD.

2021-04-19 17:04 UTC, mmattel commented
@ib-mlatin many thanks for your PR. I need to rewrite it a bit but this is not a big deal.

2021-06-21 06:24 UTC, mmattel commented
Desktop/mobile apps do not work by default with OICD (MS-Azure is just one possible Idp...)
Improved the text and relocated to the parent level (OIDC)

2021-06-21 06:36 UTC, phil-davis approved these changes
English looks OK to me.

2021-06-21 10:09 UTC, michaelstingl requested changes
Comment for general OIDC doesn't make sense. Needs only comment on `ms-azure-setup.adoc` page.

2021-06-21 11:44 UTC, phil-davis commented on modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
> +NOTE: The desktop and mobile apps (clients) have a default client ID and secret hardcoded, used for ownCloud's oauth2 app. When using Kopano as IDP, it does not predefine a client ID and secret. You
```suggestion
NOTE: The desktop and mobile apps (clients) have a default client ID and secret hardcoded, used for ownCloud's oauth2 app. When using Kopano as IDP, it does not predefine a client ID and secret. You can use the default ones from the client to configure Kopano properly. For some IDP's like MS-Azure, these and other required parameters come from the IDP and must be coded into the client. Note that each IDP has different requirements. Get in touch with ownCloud for a branding subscription to customize the clients according your needs.
```

2021-06-22 04:33 UTC, EParzefall approved these changes
Minor language issues.

2021-06-22 04:33 UTC, EParzefall commented on modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
> +NOTE: The desktop and mobile apps (clients) have a default client ID and secret hardcoded, used for ownCloud's oauth2 app. When using Kopano as IDP, it does not predefine a client ID and secret. You
```suggestion
NOTE: The desktop and mobile apps (clients) have a default client ID and secret hard-coded, which are used for ownCloud's oauth2 app. When using Kopano as IDP, it does not pre-define a client ID and secret. You can use the default ones of the client to configure Kopano properly. With some IDPs like MS-Azure, these and other required parameters come from the IDP and must be coded into the client. Note that each IDP has different requirements. Get in touch with ownCloud for a branding subscription to customize the clients according to your needs.
```

2021-06-22 05:27 UTC, phil-davis approved these changes
This reads OK to me. Someone else knows if it is exactly correct!

2021-06-22 05:43 UTC, merged