Use the new docs ios repo
owncloud/docs pull request #4047
Opened 2021-09-16 19:47 UTC by mmattel

This PR enables the new `docs-client-ios-app` as base for the iOS documentation.

That repo has been prepared including a master (next) branch and the currently stable branch 11.7
Builds for html and pdf including master and 11.7 run fine.

If there is a new iOS version coming, we can proceed as usual in the `docs-client-ios-app`, only an adoption of `site.yml` and the `release.adoc` file in this repo is necessary (plus backports).

The `previous-ios-version` attribute has been added in advance, but is currently unused until a new ios version will be published.

Dependency: https://github.com/owncloud/docs-client-ios-app/issues/2 (Enable CI)

Note that there is (most likely) a manual intervention necessary to tag `latest` for iOS to 11.7 in gitea

Backports to 10.8 and 10.7

@EParzefall @phil-davis fyi

2021-09-16 19:58 UTC, mmattel commented
Note that the failing CI is due to the fact, that owncloud/docs-client-ios-app#2 needs to be fixed to make CI here happy. If done, CI needs a restart

2021-09-17 08:59 UTC, xoxys commented
> Note that the failing CI is due to the fact, that [owncloud/docs-client-ios-app#2](https://github.com/owncloud/docs-client-ios-app/issues/2) needs to be fixed to make CI here happy. If done, CI needs a restart

That's simply not true, read the [error log](https://drone.owncloud.com/owncloud/docs/12725/2/4): 

```
Error: antora.yml not found in https://github.com/owncloud/docs-client-ios-app.git (ref: remotes/origin/11.7 | path: docs)
```

That's because you have an issue in this PR at https://github.com/owncloud/docs/blob/e91449fedcd8e22b0e0a89cfc2607297ccfd04fe/site.yml#L22 as the new repo does not use `./docs` as base path anymore...

2021-09-17 08:59 UTC, xoxys requested changes
See comment

2021-09-17 15:11 UTC, mmattel commented
The false doc root for ios has been fixed, CI is green now

2021-09-20 11:23 UTC, xoxys approved these changes

2021-09-20 12:51 UTC, merged