Server 10.10 Release Notes
owncloud/docs pull request #4730
Opened 2022-05-05 13:07 UTC by pmaier1

draft mode, still some things missing

2022-05-05 14:34 UTC, phil-davis commented on modules/ROOT/pages/server_release_notes.adoc
> +* Group administrators will now only see the groups they are an administrator of in user management (previously they also so other groups but were unable to manage them). https://github.com/owncloud/
```suggestion
* Group administrators will now only see the groups they are an administrator of in user management (previously they also saw other groups but were unable to manage them). https://github.com/owncloud/core/pull/39752[#39752]
```

2022-05-05 14:40 UTC, phil-davis commented on modules/ROOT/pages/server_release_notes.adoc
> +=== For developers
Maybe also mention 
"Enhancement - Expose user type of share receiver in share api: [#40013](https://github.com/owncloud/core/pull/40013)"
?

That is another addition to data returned in an API response.

2022-05-13 07:42 UTC, jnweiger commented on modules/ROOT/pages/server_release_notes.adoc
> +* A new config option `session_forced_logout_timeout` has been introduced in `config.php`. For advanced security, this option can be used to expire user sessions a configurable amount of seconds afte
```suggestion
* A new config option `session_forced_logout_timeout` has been introduced in `config.php`. For advanced security, this option can be used to expire user sessions a configurable amount of seconds after they close the ownCloud browser tab or the whole browser, respectively, forcing the user to log in again, when they access ownCloud the next time. This option is disabled by default.
```

2022-05-13 07:43 UTC, jnweiger commented on modules/ROOT/pages/server_release_notes.adoc
> +* A new config option `session_forced_logout_timeout` has been introduced in `config.php`. For advanced security, this option can be used to expire user sessions a configurable amount of seconds afte
duplicate the the

2022-05-13 08:08 UTC, jnweiger requested changes
One duplicate word 'the the' and one contradiction found.

2022-05-13 08:12 UTC, pmaier1 commented on modules/ROOT/pages/server_release_notes.adoc
> +* ownCloud Server 10.9 introduced a new feature to xref:server_release_notes.adoc#highly-improved-initial-sync-and-discovery-performance[improve initial sync and discovery performance] which has been
Not really. In 10.9 it's enabled by default. 10.10 changes that to disabled by default.

2022-05-19 08:28 UTC, pmaier1 commented
This is ready for final review/merge.

2022-05-19 08:35 UTC, mmattel approved these changes
After a discussion with @pmaier1, the content ist fine, any changes needed can be fixed afterwards - approving

2022-05-19 08:39 UTC, merged